#spring.devtools.remote.restart.enabled=true
prod.mails: aa@c.com, aas@sss.com
prod.notification: false
# Enable graceful shutdown, values: GRACEFUL, IMMEDIATE
server.shutdown: graceful
spring.lifecycle.timeout-per-shutdown-phase: 30s



# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /doc
